[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

  # This is how we can make some data at build and/or deploy-time and have it look
  # like a regular API call to the client. In this case, the client GET /api/misc
  # is returned the static JSON file without going through a function.

  [[redirects]]
    from = "/api/misc"
    to = "/static-api/misc.json"
    status = 200
    headers = {"Content-Type" = "application/json"}
    force = true

  [[redirects]]
    from = "/api/misc/:id"
    to = "/static-api/misc/:id.json"
    status = 200
    headers = {"Content-Type" = "application/json"}
    force = true

  # Redirects all traffic to index.html for SPAs like Ember
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  ## Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  [dev]
    # We use the special value of '#custom' to let `netlify dev` know not to make
    # any assumptions
    framework = "#custom"
  
    # `netlify dev` runs this command and waits for the targetPort below to be ready.
    # In our Ember app, that happens when Vite does it's thing.
    command = "pnpm run start:ember"
    targetPort = 4200

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
