name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: "25.9.0"
          pnpm-version: "10.33.2"
      - run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: "25.9.0"
          pnpm-version: "10.33.2"
      - name: Install Playwright Chromium
        run: pnpm exec playwright install --with-deps chromium
      - run: pnpm test:ci
